import type {
  FunctionDefinition,
  FunctionId,
  MainFunctionId,
} from './types'

const EPSILON = 1e-10

const evaluators = {
  sin: Math.sin,
  cos: Math.cos,
  tan: Math.tan,
  cot: (x: number) => 1 / Math.tan(x),
  sec: (x: number) => 1 / Math.cos(x),
  csc: (x: number) => 1 / Math.sin(x),
  arcsin: Math.asin,
  arccos: Math.acos,
  arctan: Math.atan,
  arccot: (x: number) => Math.atan2(1, x) > 0 ? Math.atan2(1, x) : Math.atan2(1, x) + Math.PI,
  arcsec: (x: number) => Math.acos(1 / x),
  arccsc: (x: number) => Math.asin(1 / x),
} satisfies Record<FunctionId, (x: number) => number>

const isFiniteReal = (x: number) => Number.isFinite(x)
const isUnitInterval = (x: number) =>
  Number.isFinite(x) && x >= -1 && x <= 1
const isOutsideUnitInterval = (x: number) =>
  Number.isFinite(x) && Math.abs(x) >= 1

export const trigFunctionIds =
  ['sin', 'cos', 'tan', 'cot', 'sec', 'csc'] as const satisfies readonly FunctionId[]

export const inverseFunctionIds =
  ['arcsin', 'arccos', 'arctan', 'arccot'] as const satisfies readonly FunctionId[]

export const supplementFunctionIds =
  ['arcsec', 'arccsc'] as const satisfies readonly FunctionId[]

export const mainFunctionIds =
  [...trigFunctionIds, ...inverseFunctionIds] as const satisfies readonly MainFunctionId[]

export const functionCatalog = [
  {
    id: 'sin',
    category: 'trig',
    name: '正弦函数',
    formula: 'y = \\sin x',
    domain: '\\mathbb{R}',
    range: '[-1, 1]',
    parity: '奇函数',
    increasingIntervals: ['[-\\pi/2 + 2k\\pi, \\pi/2 + 2k\\pi]'],
    decreasingIntervals: ['[\\pi/2 + 2k\\pi, 3\\pi/2 + 2k\\pi]'],
    period: '2\\pi',
    zeros: 'x = k\\pi',
    extrema: '最大值 1：x = \\pi/2 + 2k\\pi；最小值 -1：x = -\\pi/2 + 2k\\pi',
    verticalAsymptotes: [],
    horizontalAsymptotes: [],
    continuousIntervals: ['\\mathbb{R}'],
    derivative: '\\cos x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'sin-zero-neg-pi', x: -Math.PI, y: 0, xLabel: '-\\pi', yLabel: '0', kind: 'zero' },
      { id: 'sin-min-neg-half-pi', x: -Math.PI / 2, y: -1, xLabel: '-\\pi/2', yLabel: '-1', kind: 'minimum' },
      { id: 'sin-zero-0', x: 0, y: 0, xLabel: '0', yLabel: '0', kind: 'zero' },
      { id: 'sin-max-half-pi', x: Math.PI / 2, y: 1, xLabel: '\\pi/2', yLabel: '1', kind: 'maximum' },
      { id: 'sin-zero-pi', x: Math.PI, y: 0, xLabel: '\\pi', yLabel: '0', kind: 'zero' },
    ],
    evaluate: evaluators.sin,
    isDefined: isFiniteReal,
    inverseRelation: {
      originalId: 'sin',
      inverseId: 'arcsin',
      restriction: '[-\\pi/2, \\pi/2]',
      restrictionBounds: { min: -Math.PI / 2, max: Math.PI / 2, minOpen: false, maxOpen: false },
    },
    style: { color: '#2563eb', darkColor: '#60a5fa', pattern: 'solid', label: '\\sin x' },
  },
  {
    id: 'cos',
    category: 'trig',
    name: '余弦函数',
    formula: 'y = \\cos x',
    domain: '\\mathbb{R}',
    range: '[-1, 1]',
    parity: '偶函数',
    increasingIntervals: ['[(2k-1)\\pi, 2k\\pi]'],
    decreasingIntervals: ['[2k\\pi, (2k+1)\\pi]'],
    period: '2\\pi',
    zeros: 'x = \\pi/2 + k\\pi',
    extrema: '最大值 1：x = 2k\\pi；最小值 -1：x = \\pi + 2k\\pi',
    verticalAsymptotes: [],
    horizontalAsymptotes: [],
    continuousIntervals: ['\\mathbb{R}'],
    derivative: '-\\sin x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'cos-min-neg-pi', x: -Math.PI, y: -1, xLabel: '-\\pi', yLabel: '-1', kind: 'minimum' },
      { id: 'cos-zero-neg-half-pi', x: -Math.PI / 2, y: 0, xLabel: '-\\pi/2', yLabel: '0', kind: 'zero' },
      { id: 'cos-max-0', x: 0, y: 1, xLabel: '0', yLabel: '1', kind: 'maximum' },
      { id: 'cos-zero-half-pi', x: Math.PI / 2, y: 0, xLabel: '\\pi/2', yLabel: '0', kind: 'zero' },
      { id: 'cos-min-pi', x: Math.PI, y: -1, xLabel: '\\pi', yLabel: '-1', kind: 'minimum' },
    ],
    evaluate: evaluators.cos,
    isDefined: isFiniteReal,
    inverseRelation: {
      originalId: 'cos',
      inverseId: 'arccos',
      restriction: '[0, \\pi]',
      restrictionBounds: { min: 0, max: Math.PI, minOpen: false, maxOpen: false },
    },
    style: { color: '#dc2626', darkColor: '#f87171', pattern: 'dashed', label: '\\cos x' },
  },
  {
    id: 'tan',
    category: 'trig',
    name: '正切函数',
    formula: 'y = \\tan x',
    domain: '\\mathbb{R} \\setminus \\{\\pi/2 + k\\pi\\}',
    range: '\\mathbb{R}',
    parity: '奇函数',
    increasingIntervals: ['(-\\pi/2 + k\\pi, \\pi/2 + k\\pi)'],
    decreasingIntervals: [],
    period: '\\pi',
    zeros: 'x = k\\pi',
    extrema: '无最大值和最小值',
    verticalAsymptotes: ['x = \\pi/2 + k\\pi'],
    horizontalAsymptotes: [],
    continuousIntervals: ['(-\\pi/2 + k\\pi, \\pi/2 + k\\pi)'],
    derivative: '\\sec^2 x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'tan-key-neg-quarter-pi', x: -Math.PI / 4, y: -1, xLabel: '-\\pi/4', yLabel: '-1', kind: 'key' },
      { id: 'tan-zero-0', x: 0, y: 0, xLabel: '0', yLabel: '0', kind: 'zero' },
      { id: 'tan-key-quarter-pi', x: Math.PI / 4, y: 1, xLabel: '\\pi/4', yLabel: '1', kind: 'key' },
    ],
    evaluate: evaluators.tan,
    isDefined: x => Number.isFinite(x) && Math.abs(Math.cos(x)) > EPSILON,
    inverseRelation: {
      originalId: 'tan',
      inverseId: 'arctan',
      restriction: '(-\\pi/2, \\pi/2)',
      restrictionBounds: { min: -Math.PI / 2, max: Math.PI / 2, minOpen: true, maxOpen: true },
    },
    style: { color: '#16a34a', darkColor: '#4ade80', pattern: 'dash-dot', label: '\\tan x' },
  },
  {
    id: 'cot',
    category: 'trig',
    name: '余切函数',
    formula: 'y = \\cot x',
    domain: '\\mathbb{R} \\setminus \\{k\\pi\\}',
    range: '\\mathbb{R}',
    parity: '奇函数',
    increasingIntervals: [],
    decreasingIntervals: ['(k\\pi, (k+1)\\pi)'],
    period: '\\pi',
    zeros: 'x = \\pi/2 + k\\pi',
    extrema: '无最大值和最小值',
    verticalAsymptotes: ['x = k\\pi'],
    horizontalAsymptotes: [],
    continuousIntervals: ['(k\\pi, (k+1)\\pi)'],
    derivative: '-\\csc^2 x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'cot-key-quarter-pi', x: Math.PI / 4, y: 1, xLabel: '\\pi/4', yLabel: '1', kind: 'key' },
      { id: 'cot-zero-half-pi', x: Math.PI / 2, y: 0, xLabel: '\\pi/2', yLabel: '0', kind: 'zero' },
      { id: 'cot-key-three-quarter-pi', x: 3 * Math.PI / 4, y: -1, xLabel: '3\\pi/4', yLabel: '-1', kind: 'key' },
    ],
    evaluate: evaluators.cot,
    isDefined: x => Number.isFinite(x) && Math.abs(Math.sin(x)) > EPSILON,
    inverseRelation: {
      originalId: 'cot',
      inverseId: 'arccot',
      restriction: '(0, \\pi)',
      restrictionBounds: { min: 0, max: Math.PI, minOpen: true, maxOpen: true },
    },
    style: { color: '#9333ea', darkColor: '#c084fc', pattern: 'dotted', label: '\\cot x' },
  },
  {
    id: 'sec',
    category: 'trig',
    name: '正割函数',
    formula: 'y = \\sec x',
    domain: '\\mathbb{R} \\setminus \\{\\pi/2 + k\\pi\\}',
    range: '(-\\infty, -1] \\cup [1, +\\infty)',
    parity: '偶函数',
    increasingIntervals: [
      '(2k\\pi, \\pi/2 + 2k\\pi)',
      '(\\pi/2 + 2k\\pi, \\pi + 2k\\pi)',
    ],
    decreasingIntervals: [
      '(-\\pi/2 + 2k\\pi, 2k\\pi)',
      '(\\pi + 2k\\pi, 3\\pi/2 + 2k\\pi)',
    ],
    period: '2\\pi',
    zeros: '无零点',
    extrema: '局部最小值 1：x = 2k\\pi；局部最大值 -1：x = \\pi + 2k\\pi',
    verticalAsymptotes: ['x = \\pi/2 + k\\pi'],
    horizontalAsymptotes: [],
    continuousIntervals: ['(-\\pi/2 + k\\pi, \\pi/2 + k\\pi)'],
    derivative: '\\sec x \\tan x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'sec-local-max-neg-pi', x: -Math.PI, y: -1, xLabel: '-\\pi', yLabel: '-1', kind: 'maximum' },
      { id: 'sec-local-min-0', x: 0, y: 1, xLabel: '0', yLabel: '1', kind: 'minimum' },
      { id: 'sec-local-max-pi', x: Math.PI, y: -1, xLabel: '\\pi', yLabel: '-1', kind: 'maximum' },
      { id: 'sec-local-min-two-pi', x: 2 * Math.PI, y: 1, xLabel: '2\\pi', yLabel: '1', kind: 'minimum' },
    ],
    evaluate: evaluators.sec,
    isDefined: x => Number.isFinite(x) && Math.abs(Math.cos(x)) > EPSILON,
    style: { color: '#ea580c', darkColor: '#fb923c', pattern: 'dashed', label: '\\sec x' },
  },
  {
    id: 'csc',
    category: 'trig',
    name: '余割函数',
    formula: 'y = \\csc x',
    domain: '\\mathbb{R} \\setminus \\{k\\pi\\}',
    range: '(-\\infty, -1] \\cup [1, +\\infty)',
    parity: '奇函数',
    increasingIntervals: [
      '(\\pi/2 + 2k\\pi, \\pi + 2k\\pi)',
      '(\\pi + 2k\\pi, 3\\pi/2 + 2k\\pi)',
    ],
    decreasingIntervals: [
      '(2k\\pi, \\pi/2 + 2k\\pi)',
      '(3\\pi/2 + 2k\\pi, 2\\pi + 2k\\pi)',
    ],
    period: '2\\pi',
    zeros: '无零点',
    extrema: '局部最小值 1：x = \\pi/2 + 2k\\pi；局部最大值 -1：x = 3\\pi/2 + 2k\\pi',
    verticalAsymptotes: ['x = k\\pi'],
    horizontalAsymptotes: [],
    continuousIntervals: ['(k\\pi, (k+1)\\pi)'],
    derivative: '-\\csc x \\cot x',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'csc-local-max-neg-half-pi', x: -Math.PI / 2, y: -1, xLabel: '-\\pi/2', yLabel: '-1', kind: 'maximum' },
      { id: 'csc-local-min-half-pi', x: Math.PI / 2, y: 1, xLabel: '\\pi/2', yLabel: '1', kind: 'minimum' },
      { id: 'csc-local-max-three-half-pi', x: 3 * Math.PI / 2, y: -1, xLabel: '3\\pi/2', yLabel: '-1', kind: 'maximum' },
    ],
    evaluate: evaluators.csc,
    isDefined: x => Number.isFinite(x) && Math.abs(Math.sin(x)) > EPSILON,
    style: { color: '#0891b2', darkColor: '#22d3ee', pattern: 'dash-dot', label: '\\csc x' },
  },
  {
    id: 'arcsin',
    category: 'inverse',
    name: '反正弦函数',
    formula: 'y = \\arcsin x',
    domain: '[-1, 1]',
    range: '[-\\pi/2, \\pi/2]',
    principalRange: '[-\\pi/2, \\pi/2]',
    parity: '奇函数',
    increasingIntervals: ['[-1, 1]'],
    decreasingIntervals: [],
    period: '无周期',
    zeros: 'x = 0',
    extrema: '最小值 -\\pi/2：x = -1；最大值 \\pi/2：x = 1',
    verticalAsymptotes: [],
    horizontalAsymptotes: [],
    continuousIntervals: ['[-1, 1]'],
    derivative: '\\frac{1}{\\sqrt{1-x^2}},\\quad -1 < x < 1',
    endpointNotes: ['x = \\pm 1 处导数不存在且具有竖直切线'],
    limitNotes: [],
    keyPoints: [
      { id: 'arcsin-min-neg-one', x: -1, y: -Math.PI / 2, xLabel: '-1', yLabel: '-\\pi/2', kind: 'minimum' },
      { id: 'arcsin-origin', x: 0, y: 0, xLabel: '0', yLabel: '0', kind: 'zero' },
      { id: 'arcsin-max-one', x: 1, y: Math.PI / 2, xLabel: '1', yLabel: '\\pi/2', kind: 'maximum' },
    ],
    evaluate: evaluators.arcsin,
    isDefined: isUnitInterval,
    inverseRelation: {
      originalId: 'sin',
      inverseId: 'arcsin',
      restriction: '[-\\pi/2, \\pi/2]',
      restrictionBounds: { min: -Math.PI / 2, max: Math.PI / 2, minOpen: false, maxOpen: false },
    },
    style: { color: '#1d4ed8', darkColor: '#93c5fd', pattern: 'solid', label: '\\arcsin x' },
  },
  {
    id: 'arccos',
    category: 'inverse',
    name: '反余弦函数',
    formula: 'y = \\arccos x',
    domain: '[-1, 1]',
    range: '[0, \\pi]',
    principalRange: '[0, \\pi]',
    parity: '非奇非偶',
    increasingIntervals: [],
    decreasingIntervals: ['[-1, 1]'],
    period: '无周期',
    zeros: 'x = 1',
    extrema: '最大值 \\pi：x = -1；最小值 0：x = 1',
    verticalAsymptotes: [],
    horizontalAsymptotes: [],
    continuousIntervals: ['[-1, 1]'],
    derivative: '-\\frac{1}{\\sqrt{1-x^2}},\\quad -1 < x < 1',
    endpointNotes: ['x = \\pm 1 处导数不存在且具有竖直切线'],
    limitNotes: ['\\arccos x = \\pi/2 - \\arcsin x'],
    keyPoints: [
      { id: 'arccos-max-neg-one', x: -1, y: Math.PI, xLabel: '-1', yLabel: '\\pi', kind: 'maximum' },
      { id: 'arccos-key-origin', x: 0, y: Math.PI / 2, xLabel: '0', yLabel: '\\pi/2', kind: 'key' },
      { id: 'arccos-zero-one', x: 1, y: 0, xLabel: '1', yLabel: '0', kind: 'minimum' },
    ],
    evaluate: evaluators.arccos,
    isDefined: isUnitInterval,
    inverseRelation: {
      originalId: 'cos',
      inverseId: 'arccos',
      restriction: '[0, \\pi]',
      restrictionBounds: { min: 0, max: Math.PI, minOpen: false, maxOpen: false },
    },
    style: { color: '#b91c1c', darkColor: '#fca5a5', pattern: 'dashed', label: '\\arccos x' },
  },
  {
    id: 'arctan',
    category: 'inverse',
    name: '反正切函数',
    formula: 'y = \\arctan x',
    domain: '\\mathbb{R}',
    range: '(-\\pi/2, \\pi/2)',
    principalRange: '(-\\pi/2, \\pi/2)',
    parity: '奇函数',
    increasingIntervals: ['\\mathbb{R}'],
    decreasingIntervals: [],
    period: '无周期',
    zeros: 'x = 0',
    extrema: '无最大值和最小值',
    verticalAsymptotes: [],
    horizontalAsymptotes: ['y = -\\pi/2', 'y = \\pi/2'],
    continuousIntervals: ['\\mathbb{R}'],
    derivative: '\\frac{1}{1+x^2}',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'arctan-key-neg-one', x: -1, y: -Math.PI / 4, xLabel: '-1', yLabel: '-\\pi/4', kind: 'key' },
      { id: 'arctan-origin', x: 0, y: 0, xLabel: '0', yLabel: '0', kind: 'zero' },
      { id: 'arctan-key-one', x: 1, y: Math.PI / 4, xLabel: '1', yLabel: '\\pi/4', kind: 'key' },
    ],
    evaluate: evaluators.arctan,
    isDefined: isFiniteReal,
    inverseRelation: {
      originalId: 'tan',
      inverseId: 'arctan',
      restriction: '(-\\pi/2, \\pi/2)',
      restrictionBounds: { min: -Math.PI / 2, max: Math.PI / 2, minOpen: true, maxOpen: true },
    },
    style: { color: '#15803d', darkColor: '#86efac', pattern: 'dash-dot', label: '\\arctan x' },
  },
  {
    id: 'arccot',
    category: 'inverse',
    name: '反余切函数',
    formula: 'y = \\operatorname{arccot} x',
    domain: '\\mathbb{R}',
    range: '(0, \\pi)',
    principalRange: '(0, \\pi)',
    parity: '非奇非偶',
    increasingIntervals: [],
    decreasingIntervals: ['\\mathbb{R}'],
    period: '无周期',
    zeros: '无零点',
    extrema: '无最大值和最小值',
    verticalAsymptotes: [],
    horizontalAsymptotes: ['y = \\pi', 'y = 0'],
    continuousIntervals: ['\\mathbb{R}'],
    derivative: '-\\frac{1}{1+x^2}',
    endpointNotes: [],
    limitNotes: [
      'x \\to -\\infty 时，y \\to \\pi',
      'x \\to +\\infty 时，y \\to 0',
      '\\operatorname{arccot}(-x) = \\pi - \\operatorname{arccot} x',
    ],
    keyPoints: [
      { id: 'arccot-key-neg-one', x: -1, y: 3 * Math.PI / 4, xLabel: '-1', yLabel: '3\\pi/4', kind: 'key' },
      { id: 'arccot-origin', x: 0, y: Math.PI / 2, xLabel: '0', yLabel: '\\pi/2', kind: 'key' },
      { id: 'arccot-key-one', x: 1, y: Math.PI / 4, xLabel: '1', yLabel: '\\pi/4', kind: 'key' },
    ],
    evaluate: evaluators.arccot,
    isDefined: isFiniteReal,
    inverseRelation: {
      originalId: 'cot',
      inverseId: 'arccot',
      restriction: '(0, \\pi)',
      restrictionBounds: { min: 0, max: Math.PI, minOpen: true, maxOpen: true },
    },
    style: { color: '#7e22ce', darkColor: '#d8b4fe', pattern: 'dotted', label: '\\operatorname{arccot} x' },
  },
  {
    id: 'arcsec',
    category: 'supplement',
    name: '反正割函数',
    formula: 'y = \\operatorname{arcsec} x',
    domain: '(-\\infty, -1] \\cup [1, +\\infty)',
    range: '[0, \\pi] \\setminus \\{\\pi/2\\}',
    principalRange: '[0, \\pi] \\setminus \\{\\pi/2\\}',
    parity: '非奇非偶',
    increasingIntervals: ['(-\\infty, -1]', '[1, +\\infty)'],
    decreasingIntervals: [],
    period: '无周期',
    zeros: 'x = 1',
    extrema: '最小值 0：x = 1；最大值 \\pi：x = -1',
    verticalAsymptotes: [],
    horizontalAsymptotes: ['y = \\pi/2'],
    continuousIntervals: ['(-\\infty, -1]', '[1, +\\infty)'],
    derivative: '\\frac{1}{|x|\\sqrt{x^2-1}}',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'arcsec-key-neg-one', x: -1, y: Math.PI, xLabel: '-1', yLabel: '\\pi', kind: 'key' },
      { id: 'arcsec-zero-one', x: 1, y: 0, xLabel: '1', yLabel: '0', kind: 'zero' },
    ],
    evaluate: evaluators.arcsec,
    isDefined: isOutsideUnitInterval,
    conventionNote: '不同教材可能采用不同的主值范围约定；此处数值求值采用 arccos(1/x)。',
    style: { color: '#c2410c', darkColor: '#fdba74', pattern: 'dashed', label: '\\operatorname{arcsec} x' },
  },
  {
    id: 'arccsc',
    category: 'supplement',
    name: '反余割函数',
    formula: 'y = \\operatorname{arccsc} x',
    domain: '(-\\infty, -1] \\cup [1, +\\infty)',
    range: '[-\\pi/2, \\pi/2] \\setminus \\{0\\}',
    principalRange: '[-\\pi/2, \\pi/2] \\setminus \\{0\\}',
    parity: '奇函数',
    increasingIntervals: [],
    decreasingIntervals: ['(-\\infty, -1]', '[1, +\\infty)'],
    period: '无周期',
    zeros: '无零点',
    extrema: '最小值 -\\pi/2：x = -1；最大值 \\pi/2：x = 1',
    verticalAsymptotes: [],
    horizontalAsymptotes: ['y = 0'],
    continuousIntervals: ['(-\\infty, -1]', '[1, +\\infty)'],
    derivative: '-\\frac{1}{|x|\\sqrt{x^2-1}}',
    endpointNotes: [],
    limitNotes: [],
    keyPoints: [
      { id: 'arccsc-key-neg-one', x: -1, y: -Math.PI / 2, xLabel: '-1', yLabel: '-\\pi/2', kind: 'key' },
      { id: 'arccsc-key-one', x: 1, y: Math.PI / 2, xLabel: '1', yLabel: '\\pi/2', kind: 'key' },
    ],
    evaluate: evaluators.arccsc,
    isDefined: isOutsideUnitInterval,
    conventionNote: '不同教材可能采用不同的主值范围约定；此处数值求值采用 arcsin(1/x)。',
    style: { color: '#0e7490', darkColor: '#67e8f9', pattern: 'dash-dot', label: '\\operatorname{arccsc} x' },
  },
] as const satisfies readonly FunctionDefinition[]

const functionDefinitionById = new Map<FunctionId, FunctionDefinition>(
  functionCatalog.map(definition => [definition.id, definition]),
)

export function getFunctionDefinition(id: FunctionId): FunctionDefinition {
  const definition = functionDefinitionById.get(id)

  if (!definition) {
    throw new Error(`未知函数 ID：${id}`)
  }

  return definition
}
